<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<table>
    <thead>
    <tr>
        <th>FIRST_NAME</th>
        <th>LAST_NAME</th>
        <th>EMAIL_ID</th>
        <th>PHONE_NUMBER</th>
        <th>CITY_ID</th>
        <th>DATE_OF_BIRTH</th>
        <th>PERMANENT_ACCOUNT_NUMBER</th>
        <th>COMPANY_NAME</th>
        <th>EDUCATION</th>
        <th>NET_INCOME</th>
        <th>PROFESSION_ID</th>
        <th>CIBIL_SCORE</th>
        <th>CIBIL_STATUS_ID</th>
        <th>SALARY_BANK_NAME</th>
        <th>MARITAL_STATUS_ID</th>
        <th>RESIDENT_STATUS_ID</th>
        <th>LOAN_STATUS</th>
    </tr>
    </thead>
</table>
