<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<table>
    <thead>
    <tr>
        <th>FIRST_NAME</th>
        <th>LAST_NAME</th>
        <th>PHONE_NUMBER</th>
        <th>EMAIL_ID</th>
        <th>CITY_ID</th>
        <th>DATE_OF_BIRTH</th>
        <th>PERMANENT_ACCOUNT_NUMBER</th>
        <th>EDUCATION</th>
        <th>NET_INCOME</th>
        <th>COMPANY_NAME</th>
        <th>TYPE_ID</th>
        <th>PROPERTY_VERIFIED</th>
        <th>ASSIGNED_TO</th>
        <th>SOURCE_ID</th>
        <th>AMOUNT</th>
        <th>PROJECT_ID</th>
        <th>REFERRAL_ID</th>
        <th>EXISTING_LOAN_EMI</th>
    </tr>
    </thead>
</table>
